spring:
  application:
    name: finance-api
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_dhentech_db
    username: administrator
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false