spring:
  application:
    name: finance-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/financial_dhentech_db}
    username: ${SPRING_DATASOURCE_USERNAME:administrator}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  security:
    user:
      name: administrator
      password: admin